# Generated by Django 5.0.4 on 2025-03-09 09:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_payment_status_alter_payment_expires_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='house_videos/'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='None', max_length=255, verbose_name='image'),
        ),
    ]
